In [7]:
#operations
import torch
import numpy as np


In [9]:

tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [10]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [15]:
a=torch.add(tensor_a,tensor_b)
a


tensor([ 6,  8, 10, 12])

In [16]:
b=torch.sub(tensor_a,tensor_b)
b


tensor([-4, -4, -4, -4])

In [17]:
c=torch.mul(tensor_a,tensor_b)
c


tensor([ 5, 12, 21, 32])

In [18]:
d=torch.div(tensor_a,tensor_b)
d

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [20]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [23]:
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])