<a href="https://colab.research.google.com/github/Samueltar/pytorch-project-/blob/slashes-and-arrange/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [12]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
#reshape and view
my_torch =my_torch.reshape(2,-1)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [27]:
mytorch2=torch.arange(15)
mytorch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
mytorch2=mytorch2.reshape(3,5)
mytorch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [30]:
mytorch3=torch.arange(10)
mytorch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
#reshape
mytorch4=mytorch3.view(2,5)
mytorch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [35]:
import torch

# Contiguous tensor
x = torch.randn(4, 4)
print(x.is_contiguous())  # True
x
y_view = x.view(2, 8)
y_view
y_reshape = x.reshape(2, 8)
y_reshape
# Both are views (share memory), modifications affect original


# Non-contiguous tensor (after transpose)
z = x.transpose(0, 1)
z
print(z.is_contiguous())  # False


# z.view(2, 8)  # Raises RuntimeError

w = z.reshape(2, 8)  # Works! Returns a copy (contiguous tensor)
w
print(w.is_contiguous())  # True
# Modifications to w do NOT affect z


True
False
True
